version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "14:00"
    timezone: Europe/Lisbon
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-image
    versions:
    - 1.0.1
    - 1.1.0
    - 1.1.1
    - 1.1.2
    - 1.2.0
    - 1.2.1
    - 1.3.0
    - 1.3.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.7
    - 2.32.8
    - 2.32.9
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-emotion
    versions:
    - 6.1.0
    - 6.2.0
    - 6.3.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.1
    - 2.6.1
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@emotion/babel-preset-css-prop"
    versions:
    - 11.0.0
    - 11.2.0
  - dependency-name: "@emotion/core"
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
